# Generated by Django 5.0 on 2023-12-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0002_cinema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cinema",
            name="id",
        ),
        migrations.AddField(
            model_name="cinema",
            name="cinema_code",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
