# Generated by Django 4.2.7 on 2026-07-22 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0004_showtime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cinema",
            options={
                "ordering": ["city", "name"],
                "verbose_name": "سینما",
                "verbose_name_plural": "سینماها",
            },
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["name"],
                "verbose_name": "فیلم",
                "verbose_name_plural": "فیلم ها",
            },
        ),
        migrations.AlterModelOptions(
            name="showtime",
            options={
                "ordering": ["start_time"],
                "verbose_name": "سانس",
                "verbose_name_plural": "سانس ها",
            },
        ),
        migrations.AlterField(
            model_name="cinema",
            name="address",
            field=models.TextField(verbose_name="آدرس"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="capacity",
            field=models.PositiveIntegerField(verbose_name="ظرفیت"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="cinema_code",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="کد سینما"
            ),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="city",
            field=models.CharField(default="تهران", max_length=30, verbose_name="شهر"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="name",
            field=models.CharField(max_length=50, verbose_name="نام سینما"),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="شماره تماس"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(max_length=50, verbose_name="کارگردان"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="length",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="مدت زمان (دقیقه)",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام فیلم"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1888)],
                verbose_name="سال تولید",
            ),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="cinema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="showtimes",
                to="ticketing.cinema",
                verbose_name="نام سینما",
            ),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="free_seats",
            field=models.PositiveIntegerField(verbose_name="صندلی های خالی"),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="showtimes",
                to="ticketing.movie",
                verbose_name="نام فیلم",
            ),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="price",
            field=models.PositiveIntegerField(verbose_name="قیمت"),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="salable_seats",
            field=models.PositiveIntegerField(verbose_name="صندلی های فروشی"),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="start_time",
            field=models.DateTimeField(verbose_name="زمان شروع"),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "فروش آغاز نشده"),
                    (2, "درحال فروش بلیت"),
                    (3, "بلیت ها تمام شد"),
                    (4, "فروش بلیت بسته شد"),
                    (5, "فیلم پخش شد"),
                    (6, "سانس لغو شد"),
                ],
                default=1,
                verbose_name="وضعیت",
            ),
        ),
    ]
