# Generated by Django 4.2.7 on 2026-07-22 13:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ticketing", "0005_alter_cinema_options_alter_movie_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cinema",
            options={"ordering": ["city", "name"]},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="showtime",
            options={"ordering": ["start_time"]},
        ),
        migrations.AlterField(
            model_name="cinema",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="capacity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="cinema_code",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="city",
            field=models.CharField(default="Tehran", max_length=30),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="movie",
            name="length",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1888)]
            ),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="cinema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="showtimes",
                to="ticketing.cinema",
            ),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="free_seats",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="showtimes",
                to="ticketing.movie",
            ),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="salable_seats",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="start_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="showtime",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Sale Not Started"),
                    (2, "On Sale"),
                    (3, "Sold Out"),
                    (4, "Closed"),
                    (5, "Played"),
                    (6, "Canceled"),
                ],
                default=1,
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_count", models.PositiveIntegerField(default=1)),
                ("total_price", models.PositiveIntegerField()),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "showtime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="ticketing.showtime",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-booked_at"],
            },
        ),
    ]
