# Generated by Django 4.2.7 on 2026-07-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0006_alter_cinema_options_alter_movie_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="seat_count",
        ),
        migrations.AddField(
            model_name="showtime",
            name="rows",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="showtime",
            name="seats_per_row",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.CharField(max_length=1)),
                ("number", models.PositiveIntegerField()),
                ("is_reserved", models.BooleanField(default=False)),
                (
                    "showtime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="ticketing.showtime",
                    ),
                ),
            ],
            options={
                "ordering": ["row", "number"],
                "unique_together": {("showtime", "row", "number")},
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="seats",
            field=models.ManyToManyField(related_name="bookings", to="ticketing.seat"),
        ),
    ]
