# Generated by Django 4.2.7 on 2026-07-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0007_remove_booking_seat_count_showtime_rows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
    ]
