# Generated by Django 4.2.7 on 2026-07-23 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0008_movie_poster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="seats",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="total_price",
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BookingSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_seats",
                        to="ticketing.booking",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_seats",
                        to="ticketing.seat",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bookingseat",
            constraint=models.UniqueConstraint(
                fields=("seat",), name="unique_booked_seat"
            ),
        ),
    ]
