# Generated by Django 4.2.7 on 2026-07-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0009_remove_booking_seats_remove_booking_total_price_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="seat",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("booked", "Booked")],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="row",
            field=models.CharField(max_length=2),
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("showtime", "row", "number"), name="unique_seat_per_showtime"
            ),
        ),
        migrations.RemoveField(
            model_name="seat",
            name="is_reserved",
        ),
    ]
