# Generated by Django 6.1.1 on 2026-09-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_cinema_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='free_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
