# Generated by Django 6.1.1 on 2026-09-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_alter_showtime_free_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cinema',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
