# Generated by Django 4.2.7 on 2026-09-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                ("message", models.TextField(verbose_name="متن پیام")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس",
                "ordering": ["-created_at"],
            },
        ),
    ]
